### ISSUE TITLE
Inviting guests

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1059]
This is an umbrella issue that lists all the bits of work that need to happen in order to invite a user by his email address:
- [x] Tenants can configure email domains - PR at https://github.com/oaeproject/Hilary/pull/1202
- [x] Email verification - PR at https://github.com/oaeproject/Hilary/pull/1203 (UI not complete)
- [x] Search for users by email - PR at https://github.com/oaeproject/Hilary/pull/1204
- [ ] Share content by email
- [ ] Identify duplicates in production and deal with them

**Comment by mrvisser** [comment]
PR https://github.com/oaeproject/Hilary/pull/1224
