### ISSUE TITLE
Allow users and groups to be deleted

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1118]
It should be possible to mark users and groups as deleted/deactivate them. At that point, they should no longer show up in any searches or libraries, although should remain in the system (e.g. a content item is shared with that group). It should be possible for a tenant/global admin to list the deleted users and undelete them.

**Comment by nicolaasmatthijs** [comment]
Assigning to @simong for fix

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment]
This, as we all know, is sticky. Have any preliminary thoughts gone into this? Is this meant to, for example: When a user is deleted, *remove* that user from follower lists, group members lists, etc... ?

**Comment by mrvisser** [comment]
If a user is deleted, what should come of their email address, and the ability to create another user with the same authentication credentials?

**Comment by nicolaasmatthijs** [comment]
> When a user is deleted, remove that user from follower lists, group members lists, etc... ?

This is the current thinking:

**Users**

Deleted users should no longer show up in:

- searches
- follower/following lists

Deleted users should still show up in:

- group membership lists
- content membership lists
- comments
- etc.

**Groups**

Deleted groups should no longer show up in:

- searches
- user membership libraries

Deleted groups should still show up in:

- content membership lists
- group members lists
- etc.

I can see that there are issues connected to this and we can adjust the spec based on what's possible.

**Comment by nicolaasmatthijs** [comment]
> If a user is deleted, what should come of their email address, and the ability to create another user with the same authentication credentials?

That's a good question. I think we can start off with just keeping the associated login ids in place and disallow authenticating through them.

**Comment by nicolaasmatthijs** [comment]
@mrvisser : In case it helps, we could split this ticket in 2 parts and start off with "deleting" groups only, as that is a much more pressing production need.

**Comment by mrvisser** [comment]
@nicolaasmatthijs the design I have in mind for this will make it not too bad to simply implement user delete operations after group delete operations, but I'll make sure I get the group stuff done w/ tests first in case we want to release it early

**Comment by mrvisser** [comment]
Is there any kind of thought into what a deleted user/group looks like in a list? We probably still want to release their name and stuff, but "grey" them out so you can't click them or something?

**Comment by nicolaasmatthijs** [comment]
> Is there any kind of thought into what a deleted user/group looks like in a list? We probably still want to release their name and stuff, but "grey" them out so you can't click them or something?

@mrvisser : Correct. We want to make sure that the deleted group/user display name, profile picture, etc. are still available in the list, as well as a `deleted`/`active` flag that allows the UI to visually distinguish them from the other items.

**Comment by mrvisser** [comment]
In the case of users, do we want to treat them as though they are private and always show the Pseudonym (even if the original user profile was public)?

**Comment by nicolaasmatthijs** [comment]
@mrvisser : I think it's fine to treat them as they would have been treated before they were deleted

**Comment by nicolaasmatthijs** [comment]
@mrvisser : How much work would it be to finish this off and bring in user removal as well? I think it would help us work through the clean-up of the duplicate user accounts.

**Comment by mrvisser** [comment]
@nicolaasmatthijs I'd estimate about a week assuming there aren't any nasty "restore" caveats (hard to consider everything without starting implementation) I haven't thought of. That time would be mostly tests, I think.

That's also assuming no migration/merge functionality is implemented for users.

**Comment by nicolaasmatthijs** [comment]
This is being dealt with in different PRs
