### ISSUE TITLE
Deleting a comment in a private discussion in which I'm only a member results in a 401

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1129]
At a quick glance, I believe this can be traced down to the `AuthzAPI.resolveImplicitRole`.

None of the branches will be executed and the final callback will be executed. This does not return the `canInteract` information however. When it goes back up to `canDeleteDiscussionMessage` in the discussion authz api the `} else if (canInteract && message.createdBy === user.id) {` branch will never be executed as `canInteract` will be undefined.

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix

**Comment by mrvisser** [comment]
Closing in favour of #1132
