### ISSUE TITLE
Email domain regexp

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/Hilary#1154]
Rather than use a regexp for email domains, it's probably better to just use a simple prefix wildcard. Currently the expectation is that Global Admin specifies Regexp into the field, but it's too powerful than necessary and makes it impossible to detect if two email domain expressions conflict with one another.

With a prefix wildcard we should be able to validate domain conflicts with existing emails, which implies either we would need validation for config properties (which we have desired in the past) or email domains could be a tenant attribute like host instead of a config property.

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Can this ticket be closed because of inviting guests?

**Comment by mrvisser** [comment]
yessir
