### ISSUE TITLE
Include `etc` when creating a release

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1157]
This is strictly a ticket for [oae-release-tools](https://github.com/oaeproject/oae-release-tools) but that doesn't have any issues.

We should include the `etc` directory when creating tarballs as those contain the migration scripts. It's probably a matter of adding the directory under https://github.com/oaeproject/oae-release-tools/blob/master/lib/package/util.js#L70

**Comment by simong** [comment]
Assigning to @davidoae to get him familiar with the packaging tools

**Comment by davidoae** [comment]
Created PR https://github.com/oaeproject/oae-release-tools/pull/1

**Comment by simong** [comment]
This has been merged into oae-release-tools, thanks @davidoae !
