### ISSUE TITLE
Allow for searching within your items only

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1159]
Add a scope parameter that allows for searching within

- My Library, the libraries of the groups you're a member of and the folders you're a member of
- Your folders and the folders in the groups you're a member of
- Your direct and indirect group memberships
- Your followers and followees

In other words, do a search within everything that's somehow associated to you.

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser as next priority following group profiles

**Comment by SamPeck** [comment]
![oaesearchamends_v05](https://cloud.githubusercontent.com/assets/1489257/6857888/ec69ecce-d401-11e4-9b3f-0c4143720e0c.png)

**Comment by mrvisser** [comment]
Twist: Add the ability to search for all of them at the same time. :) That will take some thought.

**Comment by nicolaasmatthijs** [comment]
Isn't it basically a general search minus loggedin and public stuff ?

**Comment by mrvisser** [comment]
I'm assuming we want to include loggedin and public stuff? Especially for followers/following, which would always return nothing if it was only private

**Comment by mrvisser** [comment]
I think if we think through the filters and make it modular enough, we might be able to do facet counts if that's useful. But like I said, needs more thought to avoid mashing together an unmaintainable soup of filters.

**Comment by nicolaasmatthijs** [comment]
> I'm assuming we want to include loggedin and public stuff? Especially for followers/following, which would always return nothing if it was only private

Yes, but only those that are somehow associated to yourself.

**Comment by nicolaasmatthijs** [comment]
Closing in favour of https://github.com/oaeproject/Hilary/pull/1161
