### ISSUE TITLE
Some users are not returned in search

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1164]
We received the following bug report, which is preventing people from being added to a new group:

```
I'm having some problems trying to add students to a new group in OAE. The problem is that I can't find them on the search box. I even tried to find them as an admin and I can't either. Not even searching by email (I thought that maybe they changed their names). 

The weird thing is that I had no problem finding them a month ago for our latest course. 

I attach an image with three screenshots representitive of what I did. 

The two students are: 

ELIA PEREZ, GALA ADELA      galaadela.elia@um.es
GOMEZ REDONDO, Mª DEL CARMEN    mcarmen.gomez3@um.es

The problem is that I can't find and therefore, I can't add them.

New group where I can't add the two students: https://umu.oaeproject.org/group/umu/41ez67fe/members
Group from a month ago where you can see the student 'GALA ADELA ELIA PEREZ': https://umu.oaeproject.org/group/umu/mkN-afRK/members
```

![oae-problem](https://cloud.githubusercontent.com/assets/109850/7221601/b7a6769a-e6a5-11e4-8a4a-e1be2b4c80a0.jpg)

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for investigation. Note that this is a priority as this is a production problem and is preventing them from using the system.

**Comment by mrvisser** [comment]
This is a side-effect of some of the faulty reindex-all issues we've been having. A reindexAll did not pick these users up in the index.

I've been able to force these users to be re-indexed so the user can continue setting up their group. However the reindex issue needs to be sorted.

I'll create another ticket for that.

**Comment by mrvisser** [comment]
Closing for #1165
