### ISSUE TITLE
Reindex All doesn't reindex all documents

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/Hilary#1165]
It appears reindex-all doesn't reindex everything in production. No logs indicating what might be wrong.

It's likely this can only be reproduced in staging with a mirror of production data, unfortunately.

**Comment by nicolaasmatthijs** [comment]
@simong : Would you be able to look into this? We've received another report about users not being available in search:

```
I was not able to find a couple of users in OAE when trying to add them to a group.

The users are:

   - MARTA SÁNCHEZ MANZANARES 
   - MARIA BELEN ALONSO COSTA

I'm sure they were active users before, I've checked the activity feed and here are a couple of screenshots which shows previous activity from them:
```

![captura de pantalla 2015-05-14 a las 0 09 34](https://cloud.githubusercontent.com/assets/109850/7635139/0a91e124-fa14-11e4-90a2-ad5865387dd0.png)
![captura de pantalla 2015-05-14 a las 0 08 49](https://cloud.githubusercontent.com/assets/109850/7635140/0bf7495a-fa14-11e4-817c-58411835b5ca.png)

**Comment by nicolaasmatthijs** [comment]
This issue has now been resolved.
