### ISSUE TITLE
Group membership API not honoring parameters

### ISSUE THREAD

**Issue by sathomas** [oaeproject/Hilary#1169]
This might be intentional, but it is a bit problematic. (And it's not documented in the Swagger docs.) The API call

    https://stemincubator.oaeproject.org/api/group/g:si:41rIG10W/members?limit=50

returns only 24 results (plus a `nextToken`), although the group has well more than 24 members.

**Comment by nicolaasmatthijs** [comment]
@sathomas : The number of returned results is deliberately limited to 25 per request to avoid abuse of the REST APIs. See https://github.com/oaeproject/Hilary/blob/master/node_modules/oae-principals/lib/rest.group.js#L195

Can you confirm that 25 results are returned instead of 24 ?

**Comment by sathomas** [comment]
Yes. It's 25 not 24.

**Comment by nicolaasmatthijs** [comment]
Okay, thanks. In that case, I'm going to resolve this ticket as it is expected behavior.
