### ISSUE TITLE
Certain activities still generate emails with lines with more than a 1000 characters

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1175]
The `ACTIVITY_CONTENT_CREATE_2+_GROUP` activity for example generates the following summary: `<user> created <content1> and <content2> in the group <group>.`

Because of the CSS inlining each `<a>` tag gets about 150 characters added on top of it. This quickly blows up and crosses the postfix 1000characters threshold (even before sendgrid injects its links).

Additionally, there's a `<div class="wrapped"` on the same line that pushes that line count a bit further.

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for further investigation as this is currently a production problem.

**Comment by mrvisser** [comment]
PR at #1178
