### ISSUE TITLE
Latest OAE release breaks API

### ISSUE THREAD

**Issue by sathomas** [oaeproject/Hilary#1176]
API is generating errors for requests that worked on previous version:

`https://stemincubator.oaeproject.org/api/search/members-library/g:si:m179WbZq?scope=_tenant&limit=16`

> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

> Failed to load resource: Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers.

> XMLHttpRequest cannot load https://stemincubator.oaeproject.org/api/search/members-library/g:si:m179WbZq?scope=_tenant&limit=16. Request header field Accept-Encoding is not allowed by Access-Control-Allow-Headers.

**Comment by mrvisser** [comment]
This is strange, we haven't touched the CORS headers for 11.0.0

**Comment by sathomas** [comment]
Is there a log that can shed some light on the "Internal Server Error"?

**Comment by mrvisser** [comment]
Yes, I'm looking into it

**Comment by mrvisser** [comment]
There is no indication on the server side that there is an error. Though strange, it may be the client generating a 500 error as a result of the CORS headers response?

Just thinking out loud as I investigate more.

Note that `Accept-Encoding` has never been part of our CORS headers, so it's difficult to determine at the moment why it has just started happening. Is it perhaps a change in browser version?

**Comment by mrvisser** [comment]
I should add that we have no issue adding `Accept-Encoding`, I'm just speaking more in terms of regression.

**Comment by sathomas** [comment]
Hmm. Does seem to affect only Safari. But I haven't updated Safari in a while. Also affects Mobile Safari on iPhone.

**Comment by mrvisser** [comment]
@sathomas don't forget to add a referrer header for your options requests :) `Referrer: /` should suffice assuming you're trying from something like curl

**Comment by sathomas** [comment]
Actually, this is plain old jQuery `$.ajax()` called from within Backbone.js.

**Comment by sathomas** [comment]
Could it be something with the redirection from `members` to `members-library`?

**Comment by sathomas** [comment]
Ahh, here's what's happening. When Safari gets the redirect, it first sends an `OPTIONS` request to the new URL. That's where the error occurs.

**Comment by mrvisser** [comment]
That could be, redirection would drop headers. Though are you checking first at `members-library` then falling back? I remembered you mentioned something about that.

**Comment by sathomas** [comment]
The production site is still using the old code. Let me try pushing an update to make sure it clears the error.

**Comment by mrvisser** [comment]
Hmm, we currently don't support the `OPTIONS` request I don't think, as it shouldn't be necessary for GET requests.

**Comment by sathomas** [comment]
Yeah, not sure why Safari decides to send it.

**Comment by sathomas** [comment]
Updating the client to use the new API seems to fix it. I'll push an update to the production STEM incubator site today that should resolve this. Dang, backwards-compatibility is hard.

**Comment by mrvisser** [comment]
Yea :/ Thanks @sathomas , let me know if you need any further help / debugging from our end.

**Comment by sathomas** [comment]
It'll take me a bit to run the new code through tests (Travis CI being a slow beast at times), but once I've verified the change on production, I'll close this issue.

**Comment by sathomas** [comment]
Verified that using the updated API call directly resolves the issue.

**Comment by mrvisser** [comment]
:+1: Thanks @sathomas
