### ISSUE TITLE
Shibboleth uses email as displayName

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1177]
Following the creation of the tenancies, Jim requested that one of his contacts at Imperial tested the Shibboleth authentication. The user was able to sign in, but his email address was set as his displayName.

Can we go back and check which property we've used and whether things have been configured as expected? Are there any tweaks we can make to avoid using the email address as display name?

![image001](https://cloud.githubusercontent.com/assets/109850/7373519/e1483f50-ed81-11e4-8a49-ea26b96b007e.jpg)

**Comment by nicolaasmatthijs** [comment]
Assigning to @simong for investigation

**Comment by simong** [comment]
I already talked to Jim about this. Shibboleth isn't releasing a displayName for the user and the email address (technically eppn) is configured as the fallback.
