### ISSUE TITLE
Etherpad 1.5.6 regressions

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1184]
- The buttons to the left of the `Style` dropdown and the user button have visually regressed. They are smaller and less bold than before. The toggle authorship colors and print icons are as expected.

![screen shot 2015-05-07 at 08 50 44](https://cloud.githubusercontent.com/assets/109850/7519619/2dc08386-f496-11e4-929b-19c32d28dbdd.png)

- Toggling authorship colors no longer works
- Exporting to PDF produces a `403 - Can't touch this`

**Comment by nicolaasmatthijs** [comment]
Assigning to @simong for fix

**Comment by mrvisser** [comment]
Dixita got this error when clicking to a pad from her notifications:

```
[2015-05-07 16:11:37.538] [WARN] client - Uncaught TypeError: Cannot read property 'setChannelState' of null -- { errorId: 'JxzzmgXzz4bHwphvfwbR',
  msg: 'Uncaught TypeError: Cannot read property \'setChannelState\' of null',
  url: 'https://oae.oae-qa0.oaeproject.org/etherpad/0/p/g.QKBKAR9XsgSx5ddt$c_oae_NkxlsuE7',
  linenumber: 266,
  userAgent: 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36' }
```

I sudo'd as her and couldn't reproduce it.

**Comment by nicolaasmatthijs** [comment]
I have found a number of additional regressions:

- Line spacing has regressed, especially at the bottom of lists and around headings. You can see the difference when comparing these screenshots from production and QA1:

![screen shot 2015-05-12 at 08 42 52](https://cloud.githubusercontent.com/assets/109850/7591505/17d05f6a-f883-11e4-823f-d917a7399fb3.png)
![screen shot 2015-05-12 at 08 42 55](https://cloud.githubusercontent.com/assets/109850/7591506/180aa24c-f883-11e4-9dbc-3feb5b04abed.png)

- The size and spacing around the toolbar buttons has changed, causing the responsive behavior to no longer be as expected. The intended behavior is that, as the screen becomes smaller, the print icon disappears first, then the toggle authorship colors, then the headings dropdown (so far so good), after which the the entire toolbar should disappear.

**Comment by nicolaasmatthijs** [comment]
Sorry to be nitpicky about this, but a few small issues remain:

- The font size of the `Styles` dropdown is too small compared to what's around it. See production environment for desired font size
- The spacing below heading 4, heading 5 and heading 6 is still a bit smaller compared to the production environment. Can we replicate what's on there?

**Comment by nicolaasmatthijs** [comment]
All of the above regressions have now been fixed.
