### ISSUE TITLE
Etherpad Scrolling Problems on iOS

### ISSUE THREAD

**Issue by sathomas** [oaeproject/Hilary#1198]
An OAE issue to track iOS scrolling problems with Etherpad documents.

The main issue is assigned to [Etherpad](https://github.com/ether/etherpad-lite/issues/2224), along with a [secondary issue](https://github.com/ether/etherpad-lite/issues/2293). Etherpad has classified it as a [Safari bug](http://www.openradar.me/search?query=contenteditable). There are indications that the bug (or similar bugs) affect other online editors including [CK](http://dev.ckeditor.com/ticket/12457) [Editor](https://dev.ckeditor.com/ticket/12423) as well as [Wordpress and TinyMCE](https://core.trac.wordpress.org/ticket/30826).

Initial tests with the first beta release of iOS 9 on 2015-06-10 show that the problem still exists.

**Comment by sathomas** [comment]
There are some reports that CKEditor can avoid the problem by using the [DIV Editing Area plugin](http://ckeditor.com/addon/divarea) instead of an `<iframe>` for the content.

**Comment by sathomas** [comment]
Since Apple bug reports aren't public, I went ahead and created a simple (no dependencies, no JavaScript) [test case](https://jsfiddle.net/sathomas/rv6ktgL0/8/embedded/result/) and filed a bug report with Apple. It's number 21321546

**Comment by mrvisser** [comment]
@sathomas++ . Is that just iframing a jsfiddle edit panel in a jsfiddle?

**Comment by sathomas** [comment]
yes. the bug (apparently) only manifests in an `<iframe>`

**Comment by nicolaasmatthijs** [comment]
@sathomas : Is there more we can do here to arrive at some sort of solution or do you reckon we've run out of things we can do ourselves?

**Comment by sathomas** [comment]
I think we're done. About the only workaround I can think of is re-architecting etherpad to get rid of iframes. I'm not at all sure if John would be receptive, as that kind of drastic change probably has lots of consequences.
