### ISSUE TITLE
Youtube short URLs are parsed incorrectly

### ISSUE THREAD

**Issue by simong** [oaeproject/Hilary#1209]
For example: `youtu.be/qFfG0hlA0FU?t=131`. The ID is `qFfG0hlA0FU`, however the full path `qFfG0hlA0FU?t=131` is being used.

**Comment by nicolaasmatthijs** [comment]
Assigning to @mrvisser for fix.

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Given that having `?t=` is fairly common, would you be able to provide a fix for this that we can include in the next release?

**Comment by mrvisser** [comment]
Accidentally submit here: https://github.com/oaeproject/Hilary/pull/1211
