### ISSUE TITLE
Notification counts not working as expected

### ISSUE THREAD

**Issue by mrvisser** [oaeproject/Hilary#1256]
This is probably caused by this: https://github.com/NodeRedis/node_redis/issues/897

This bug is causing our "Mark as read" functionality to not work in production. This is mostly theorizing, so we should write a unit test that verifies it, but I think this is what is happening:

1. When a new notification comes in, the "last notification time" gets updated. This is still successful
2. When a user checks their notifications, the "notifications last read" gets updated, this is still successful
2. When a user checks their notifications, the "number of outstanding notifications" gets set to 0, this is still successful
3. When a user checks their notifications, we "mark" the feed as read by clearing all existing aggregations. This operation is now failing due to the bug.
4. When a new notification comes in, we do not increment the counter if the activity aggregates with an existing activity. This is still working successfully.

Now consider this sequence of events:

1. The user marks their notifications as read
  * The last notification time gets set to the current time successfully
  * The outstanding notifications count gets set to 0 successfully
  * The "mark" in the activity feed fails, therefore activities continue to aggregate
2. A new notification comes in that aggregates with an existing activity
  * The "last notification time" gets updated, therefore the notifications badge indicates that there are new notifications
  * Since the activity aggregates (because the mark failed), there is no increment in the notifications count

The result of this is that you see a red badge on your notifications indicator with the number 0 in it, which is clearly wrong.

A unit test should be written to verify this, running on version 2.2.5 of the node-redis module.

**Comment by mrvisser** [comment]
I have not been able to reproduce this with a test.

As per discussion in https://github.com/NodeRedis/node_redis/issues/897, it looks like this can happen with a connection loss, which is probably something that is happening when connections in production idle?

None-the-less, seems unlikely we'll get a solid regression test at our level, so lets just run the tests on the latest node-redis master and validate that this fix mentioned causes no regressions.

**Comment by nicolaasmatthijs** [comment]
Oops, I missed this. Adding notes from the duplicate ticket here:

The unread notification counts are no longer correct, which I believe has been the case since the node redis upgrade.

For example, I only had 3 actual unread notifications in the screenshot below. There were some activities where multiple files were added to a folder or a group, and it looked like the count was increased for each of those files individually.

<img width="1790" alt="screen shot 2015-11-11 at 07 37 16" src="https://cloud.githubusercontent.com/assets/109850/11095305/44f2a7d6-8849-11e5-8378-2a694cd1a0a1.png">

**Comment by nicolaasmatthijs** [comment]
@mrvisser : Can this ticket be resolved?

**Comment by mrvisser** [comment]
Yes, the redis client was upgraded and there have been no further reports or associated errors in the logs since then.
