### ISSUE TITLE
Allow tracking of user from website to OAE

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1269]
When a user goes to the OAE website (and later the *Unity website), a token should be generated for that user and stored in a cookie. This token will be used for all Mixpanel tracking on the OAE website. When the user searches for their institution and is sent off to their tenancy, there should be a way to send the token along and this token should be stored on their user profile as soon as they've signed into their tenancy.

**Comment by nicolaasmatthijs** [comment]
Assigning to @simong for fix

**Comment by brecke** [comment]
unity and mixpanel are no more
