### ISSUE TITLE
Short links in collaborative docs

### ISSUE THREAD

**Issue by davidoae** [oaeproject/Hilary#1272]
I have been asked a few times how to make a link in a collaborative doc in such a way that the whole url is displayed. Similar to an HTML <a> tag or markdown [link](http://long_url.com)
Can this reasonably be added?

**Comment by mrvisser** [comment]
It's possible we could pull something like https://www.npmjs.com/package/ep_linkify in. Though it's not markdown syntax, I'm surprised it's a syntax at all and not a toolbar icon to highlight and make something a link.

**Comment by davidoae** [comment]
This _seems_ to only make links to other etherpad docs, which, while it's
useful, appears like a halfway thing as external links are likely to be as
common.

**Comment by nicolaasmatthijs** [comment]
I'm going to add this to the design feedback and functional priorities list to ensure that we keep track of this.
