### ISSUE TITLE
Users who have not correctly populated the Name field should be hidden.

### ISSUE THREAD

**Issue by yojimbo23** [oaeproject/Hilary#1284]
If a user signs up to the service through SSO, and the service does not provide the Name attribute, it is possible for that user to drop out of the process before updating their Name and Email address.

This can result in the creation of a user with an incomprehensible name, for example "https://registry.shibboleth.ox.ac.uk/idp!https://shib-sp.unity.ac/shibboleth!ZreQ+tXFwfhw8fLHtaPStsAcHBg="

Having these users appear causes confusion for other users of the tenancy, so they should remain hidden until they update their Name (and they should be forced to do this on next login, as appears to be the case).

**Comment by nicolaasmatthijs** [comment]
Assigning to @sallakarppinen as a next ticket as it will provide some useful exposure to the auth system.

@simong @mrvisser : Feel free to add some pointers/context here.

**Comment by simong** [comment]
Most of the heavy authentication lifting is done by [Passport](http://passportjs.org/). All of the relevant glue logic (or custom authentication strategies) is contained in the `oae-authentication` module.

All the different authentication strategies have their own folder under `oae-authentication/lib/strategies/`. Each strategy should export an implementation of the `oae-authentication/lib/strategy.js` interface in its `oae-authentication/lib/strategies/<strategy name>/init.js` file. An easy example to get started with is the `Twitter` strategy as it delegates almost everything to Passport:

```javascript
strategy.shouldBeEnabled = function(tenantAlias) {
        return AuthenticationConfig.getValue(tenantAlias, AuthenticationConstants.providers.TWITTER, 'enabled');
    };
```
`shouldBeEnabled` tells you whether a strategy should be enabled for a given tenant or not. Usually this just delegates to the config api

```
strategy.getPassportStrategy = function(tenant) {
```

This function should return a  [PassportJS strateg](http://passportjs.org/). Each tenant will have its own passportjs strategy object as some of them have slightly different configuration options. As you'll notice from the Twitter `getPassportStrategy` function there are some gotcha's around changing configuration values and on-the-fly reloading of authentication strategies. (if you follow the interface, this is usually not a big problem).

All passport strategies require you to specify a callback function that specifies what needs to happen once the user is authenticated. In the case of Twitter it usually means either:
 - create a new user account if this is the first time the user signed in or
 - get the existing user account and establish a new session.
The actual getting/creating logic is abstracted in `AuthenticationUtil.handleExternalGetOrCreateUser`, you just need to pass in the user information.  That function will eventually call down to `oae-authentication/lib/api.js#getOrCreateUser`. Note that you can pass in the `visibility` as well, this will be relevant for solving this ticket. If you wanted to make all Twitter users private, you could make the following change:

```javascript
var username = profile.username;
var displayName = profile.displayName;
var opts = {};
var picture = profile['_json']['profile_image_url_https'];
if (picture) {
    // Use the better quality image
    // @see https://dev.twitter.com/docs/user-profile-images-and-banners
    picture = picture.replace(/_normal\.(.*)$/, '_bigger.$1');
    opts.smallPictureUri = 'remote:' + picture;
    opts.mediumPictureUri = 'remote:' + picture;
}

// Make all new Twitter users private
opts.visibility = 'private';

AuthenticationUtil.handleExternalGetOrCreateUser(req, AuthenticationConstants.providers.TWITTER, username, null, displayName, opts, done);
```

Now, the Shibboleth strategy is slightly more complicated as it is a custom passport strategy with a few extra components. As Shibboleth has really poor support for multi-tenant systems, there's a bit of a custom workflow (see the `README.md` in the `oae-authentication/lib/strategies/shibboleth/` directory for the full rundown.

However, passing down the profile information is exactly same as the Twitter strategy as the implemented Shibboleth strategy in its `init.js` file calls down to `AuthenticationUtil.handleExternalGetOrCreateUser` as well. Roughly, the patch would probably look something like:

```javascript
// There are a lot of SAML attributes that may indicate a user's display name. The administrator
 // should provide a suitable priority list to construct the displayname. If no suitable value was
// returned from the mapping, we fall back to the `remote_user` attribute, as this is always provided
var displayName = _getBestAttributeValue(tenant.alias, 'mapDisplayName', headers, headers['remote_user']);

// Set the optional profile parameters
var opts = {
    'authoritative': true
};

// Make the user private if their display name resembles a Shibboleth identifier (e.g., it starts with http://)
if (displayName.indexOf('http://') === 0) {
    opts.visibility = 'private';
}
```

Feel free to ping me on Slack at any time if you'd like some more info as this is not the easiest part of the stack. Good luck ;-)

**Comment by yojimbo23** [comment]
Examples of Name formats, I have come across that should be hidden include;

https://registry.shibboleth.ox.ac.uk/idp!https://shib-sp.unity.ac/shibboleth!xsAFH4Oh7H7hqELsP7ECmo/6aQQ=

and

shibboleth!wwm4Mbey7AFd1/Y+71YHzhQjvfA=

I have also come across examples where the Name field has been populated with an email address. I think these should be hidden in the same way (also it could lead to unintentionally exposing a user's email address) but there might be a counter argument I am unaware of @nicolaasmatthijs

**Comment by sallakarppinen** [comment]
I would be tempted to check for 'shibboleth!' as that seems to be the common element in those examples. Are there situations where we would expect that string in a valid Name?

**Comment by nicolaasmatthijs** [comment]
Tracked in https://github.com/oaeproject/Hilary/pull/1285
