### ISSUE TITLE
Notification emails are sent out in English

### ISSUE THREAD

**Issue by nicolaasmatthijs** [oaeproject/Hilary#1288]
Bug report from @dooremont : 

```
Since, the  update version in 12.3.1 , the notifications emails are in English. So before this update was in French ...
```

**Comment by nicolaasmatthijs** [comment]
The notification emails should be sent out in the user's language. Over to @sallakarppinen for investigation

**Comment by nicolaasmatthijs** [comment]
@dooremont : Is there any additional information you can provide about this?

**Comment by dooremont** [comment]
@nicolaasmatthijs  : We have several tenants, the ULCO tenant no problem the notifications mails are in French but in the ESUP tenant the notifications are in English.

**Comment by sallakarppinen** [comment]
@dooremont: Unfortunately I don't have access to the ESUP admin server, but could you double check that the language settings are correct in the Tenant Configuration > OAE Principals Module?

**Comment by dooremont** [comment]
@sallakarppinen : For Esup tenant : Default UI language = Français
For ULCO tenant : Default UI language = Français

{
  "oae-tenants": {
    "instance": {
      "instanceName": "OAE Esup-Portail",
      "instanceURL": "https://oae.esup-portail.org/",
      "hostingOrganization": "Consortium ESUP PORTAIL",
      "hostingOrganizationURL": "https://www.esup-portail.org/"
    },
    "actions": {
      "allowStop": false
    },
    "tenantprivacy": {
      "tenantprivate": false
    },
    "timezone": {
      "timezone": "Europe/Paris"
    },
    "guests": {
      "allow": false
    },
    "block_1": {
      "type": "search",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_2": {
      "type": "iconText",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": "### S'inscrire\r\nLa plate-forme OAE permet l'utilisation de la Fédération d'identité Renater.\r\nCela permet d'utiliser vos identifiants d'établissements (messagerie, accès à l'ENT, etc...).\r\nNéanmoins si vous n’êtes pas affilié à cette fédération ou si vous rencontrez des difficultés,\r\ncontactez : support-oae@esup-portail.org"
      },
      "icon": "fa-comments",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_3": {
      "type": "video",
      "xs": "12",
      "sm": "12",
      "md": "8",
      "lg": "8",
      "minHeight": "290",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": "# __MSG__SUPPORTING_ACADEMIC_COLLABORATION__\r\n __MSG__A_POWERFULL_NEW_WAY_FOR_STUDENTS_AND_FACULTY_TO_CREATE_KNOWLEDGE_COLLABORATE_AND_CONNECT_WITH_THE_WORLD__"
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "https://www.youtube.com/watch?v=cfiM87Y0pWw",
      "videoPlaceholder": "/ui/img/index-video-bg.png"
    },
    "block_4": {
      "type": "text",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "#FFF",
      "textColor": "#FFF",
      "text": {
        "default": "# __MSG__SUPPORTING_ACADEMIC_COLLABORATION__\r\n __MSG__A_POWERFULL_NEW_WAY_FOR_STUDENTS_AND_FACULTY_TO_CREATE_KNOWLEDGE_COLLABORATE_AND_CONNECT_WITH_THE_WORLD__"
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_5": {
      "type": "iconText",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "top",
      "bgColor": "#FFF",
      "titleColor": "#4199CA",
      "textColor": "#000",
      "text": {
        "default": "#### __MSG__AUTHORING_EXPERIENCE__\r\n __MSG__RICH_COMPELLING_INTERACTIVE_CONTENT_AUTHORING__"
      },
      "icon": "fa-edit",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_6": {
      "type": "iconText",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "top",
      "bgColor": "#424242",
      "titleColor": "#FFF",
      "textColor": "#FFF",
      "text": {
        "default": "#### __MSG__CHANNELS_OF_COMMUNICATION__\r\n __MSG__PARTICIPATING_IN_DISCUSSIONS_AND_FEEDBACK_WITHIN_PERSONALIZED_NETWORKS__"
      },
      "icon": "fa-comments",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_7": {
      "type": "iconText",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "top",
      "bgColor": "#f0EEEC",
      "titleColor": "#424242",
      "textColor": "#000",
      "text": {
        "default": "#### __MSG__ACCESS_TO_CONTENT__\r\n __MSG__EXPANDED_ACCESS_TO_LEARNING_AND_RESEARCH_MATERIALS_BETTER_CONNECTS_LIBRARY_SERVICES__"
      },
      "icon": "fa-cloud-download",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_8": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_9": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_10": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_11": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_12": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    }
  },
  "oae-authentication": {
    "local": {
      "allowAccountCreation": true,
      "enabled": true
    },
    "google": {
      "enabled": false,
      "key": "xxx",
      "secret": "xxx",
      "domains": ""
    },
    "twitter": {
      "enabled": false,
      "key": "xxx",
      "secret": "xxx"
    },
    "facebook": {
      "enabled": false,
      "appid": "xxxx",
      "secret": "xxxx"
    },
    "shibboleth": {
      "enabled": false,
      "name": "",
      "idpEntityID": "",
      "externalIdAttributes": "eppn persistent-id targeted-id",
      "mapDisplayName": "displayname cn",
      "mapEmail": "mail email eppn",
      "mapLocale": "locality locale"
    },
    "cas": {
      "enabled": true,
      "name": "la Fédération d identité Renater",
      "url": "xxxxx",
      "loginPath": "xxx",
      "useSaml": false,
      "validatePath": "/42158/serviceValidate",
      "logoutUrl": "xxxt",
      "mapDisplayName": "{cn}",
      "mapEmail": "{mail}",
      "mapLocale": ""
    },
    "ldap": {
      "enabled": false,
      "url": "",
      "adminDn": "",
      "adminPassword": "",
      "searchBase": "",
      "searchFilter": "",
      "mapExternalId": "uid",
      "mapDisplayName": "cn",
      "mapEmail": "",
      "mapLocale": ""
    }
  },
  "oae-discussions": {
    "visibility": {
      "discussion": "private"
    }
  },
  "oae-folders": {
    "visibility": {
      "folder": "private"
    }
  },
  "oae-google-analytics": {
    "google-analytics": {
      "globalEnabled": false,
      "globalTrackingId": "",
      "tenantEnabled": true,
      "tenantTrackingId": "xxxx"
    }
  },
  "oae-activity": {
    "activity": {
      "enabled": true
    }
  },
  "oae-mediacore": {
    "mediacore": {
      "enabled": false,
      "url": "",
      "keyId": "",
      "secret": "",
      "collectionId": ""
    }
  },
  "oae-content": {
    "visibility": {
      "files": "private",
      "collabdocs": "private",
      "links": "private"
    },
    "storage": {
      "backend": "local",
      "amazons3-access-key": "<access-key>",
      "amazons3-secret-key": "<secret-key>",
      "amazons3-region": "us-east-1",
      "amazons3-bucket": "oae-files"
    }
  },
  "oae-preview-processor": {
    "slideshare": {
      "apikey": "",
      "sharedsecret": ""
    },
    "flickr": {
      "apikey": "",
      "apisecret": ""
    },
    "youtube": {
      "key": ""
    }
  },
  "oae-principals": {
    "group": {
      "visibility": "private",
      "joinable": "request"
    },
    "recaptcha": {
      "enabled": true,
      "publicKey": "xxxx",
      "privateKey": "xxxx"
    },
    "termsAndConditions": {
      "enabled": true,
      "text": {
        "default": "## Déclaration des droits et responsabilités  \r\nAvant l'utilisation de la plateforme OAE, vous devez accepter les termes et conditions de son utilisation.\r\n\r\n###Votre Profil \r\nLes informations contenues dans votre profil nous permettent de communiquer avec vous notamment lors des mises à jour.\r\n\r\n###Partage de votre contenu et de vos informations\r\nLe contenu et les informations que vous publiez sur la plateforme OAE vous appartiennent. Vous pouvez contrôler la façon dont vous les partagez grâce aux paramètres d'accès :\r\n#####  * Lorsque vous publiez du contenu ou des informations avec le paramètre « Public », cela signifie que vous permettez à tout le monde, y compris les personnes n’utilisant pas la plateforme, d’accéder à ces informations et de les utiliser, mais aussi de les associer à vous (c’est-à-dire, votre nom et l’image de votre profil).\r\n#####  * Lors de la publication de ces contenus et informations, vous devez respecter les règles et législations applicables en France.\r\n#####  * Il est strictement interdit d'utiliser cette plateforme à des fins illégales et ou pour promouvoir des activités notamment dangereuses, illicites ou discriminatoires.\r\n\r\n###Disponibilité\r\nCette plateforme est en phase de pilote, et est gérée par une équipe Esup inter-universitaire.\r\nNous nous efforcerons d'assurer la continuité de service.\r\n\r\n###Sécurité\r\nNous faisons tout notre possible pour faire de cette plateforme un service sûr, mais ne pouvons pas garantir la sécurité absolue.\r\nTout élément lié à la sécurité sera remonté vers les correspondants de chaque établissement.\r\n\r\n###Protection des droits d’autrui\r\nNous respectons les droits d’autrui et nous vous demandons d'en faire de même.\r\n#####  * Nous nous réservons le droit de retirer tous contenus et informations que vous aurez publié sur la plateforme en cas de violation avec la présente Déclaration.\r\n#####  * En cas de violation, nous pourrons désactiver votre compte."
      }
    },
    "user": {
      "visibility": "public",
      "emailPreference": "daily",
      "defaultLanguage": "fr_FR"
    }
  },
  "oae-tincanapi": {
    "lrs": {
      "enabled": false,
      "username": "xxx",
      "password": "xxxx",
      "endpoint": "https://cloud.scorm.com/tc/3HQ4Q12B57/statements"
    }
  },
  "oae-ui": {
    "skin": {
      "variables": {
        "institutional-logo-url": "'https://www.esup-portail.org/sites/esup-portail.org/files/oae/esup.png'",
        "institutional-logo-small-url": "'https://www.esup-portail.org/sites/esup-portail.org/files/oae/esup_small.png'"
      }
    }
  },
  "oae-uservoice": {
    "general": {
      "enabled": false,
      "baseUrl": "",
      "subdomain": "",
      "ssoKey": ""
    }
  },
  "oae-email": {
    "general": {
      "fromName": "",
      "fromAddress": ""
    }
  }
}


_____

{
  "oae-tenants": {
    "instance": {
      "instanceName": "",
      "instanceURL": "",
      "hostingOrganization": "",
      "hostingOrganizationURL": ""
    },
    "actions": {
      "allowStop": true
    },
    "tenantprivacy": {
      "tenantprivate": false
    },
    "timezone": {
      "timezone": "Europe/Paris"
    },
    "guests": {
      "allow": false
    },
    "block_1": {
      "type": "search",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_2": {
      "type": "video",
      "xs": "12",
      "sm": "12",
      "md": "8",
      "lg": "8",
      "minHeight": "290",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "https://www.youtube.com/watch?v=cfiM87Y0pWw",
      "videoPlaceholder": "/ui/img/index-video-bg.png"
    },
    "block_3": {
      "type": "text",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "#FFF",
      "textColor": "#FFF",
      "text": {
        "default": "# __MSG__SUPPORTING_ACADEMIC_COLLABORATION__\r\n __MSG__A_POWERFULL_NEW_WAY_FOR_STUDENTS_AND_FACULTY_TO_CREATE_KNOWLEDGE_COLLABORATE_AND_CONNECT_WITH_THE_WORLD__"
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_4": {
      "type": "iconText",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "top",
      "bgColor": "#FFF",
      "titleColor": "#4199CA",
      "textColor": "#000",
      "text": {
        "default": "#### __MSG__AUTHORING_EXPERIENCE__\r\n __MSG__RICH_COMPELLING_INTERACTIVE_CONTENT_AUTHORING__"
      },
      "icon": "fa-edit",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_5": {
      "type": "iconText",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "top",
      "bgColor": "#424242",
      "titleColor": "#FFF",
      "textColor": "#FFF",
      "text": {
        "default": "#### __MSG__CHANNELS_OF_COMMUNICATION__\r\n __MSG__PARTICIPATING_IN_DISCUSSIONS_AND_FEEDBACK_WITHIN_PERSONALIZED_NETWORKS__"
      },
      "icon": "fa-comments",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_6": {
      "type": "iconText",
      "xs": "12",
      "sm": "6",
      "md": "4",
      "lg": "4",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "top",
      "bgColor": "#f0EEEC",
      "titleColor": "#424242",
      "textColor": "#000",
      "text": {
        "default": "#### __MSG__ACCESS_TO_CONTENT__\r\n __MSG__EXPANDED_ACCESS_TO_LEARNING_AND_RESEARCH_MATERIALS_BETTER_CONNECTS_LIBRARY_SERVICES__"
      },
      "icon": "fa-cloud-download",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_7": {
      "type": "video",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "https://ulco.mediacore.tv/media/teaser-oae-2/embed_player?iframe=True",
      "videoPlaceholder": "/ui/img/index-video-bg.png"
    },
    "block_8": {
      "type": "video",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "https://ulco.mediacore.tv/media/tutoriel-oae-2/embed_player?iframe=True",
      "videoPlaceholder": "/ui/img/index-video-bg.png"
    },
    "block_9": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_10": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_11": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    },
    "block_12": {
      "type": "empty",
      "xs": "12",
      "sm": "12",
      "md": "12",
      "lg": "12",
      "minHeight": "",
      "horizontalAlign": "center",
      "verticalAlign": "middle",
      "bgColor": "",
      "titleColor": "",
      "textColor": "",
      "text": {
        "default": ""
      },
      "icon": "",
      "imgUrl": "",
      "videoUrl": "",
      "videoPlaceholder": ""
    }
  },
  "oae-authentication": {
    "local": {
      "allowAccountCreation": false,
      "enabled": true
    },
    "google": {
      "enabled": false,
      "key": "xxx",
      "secret": "xxx",
      "domains": ""
    },
    "twitter": {
      "enabled": false,
      "key": "xxx",
      "secret": "xxx"
    },
    "facebook": {
      "enabled": false,
      "appid": "xxx",
      "secret": "xxx"
    },
    "shibboleth": {
      "enabled": false,
      "name": "",
      "idpEntityID": "",
      "externalIdAttributes": "eppn persistent-id targeted-id",
      "mapDisplayName": "displayname cn",
      "mapEmail": "mail email eppn",
      "mapLocale": "locality locale"
    },
    "cas": {
      "enabled": true,
      "name": "Authentification ULCO (CAS) Cliquez ici",
      "url": "xxx",
      "loginPath": "/login",
      "useSaml": false,
      "validatePath": "/serviceValidate",
      "logoutUrl": "xxxt",
      "mapDisplayName": "{displayName}",
      "mapEmail": "{mail}",
      "mapLocale": ""
    },
    "ldap": {
      "enabled": false,
      "url": "",
      "adminDn": "",
      "adminPassword": "",
      "searchBase": "",
      "searchFilter": "",
      "mapExternalId": "uid",
      "mapDisplayName": "cn",
      "mapEmail": "",
      "mapLocale": ""
    }
  },
  "oae-discussions": {
    "visibility": {
      "discussion": "private"
    }
  },
  "oae-folders": {
    "visibility": {
      "folder": "private"
    }
  },
  "oae-google-analytics": {
    "google-analytics": {
      "globalEnabled": false,
      "globalTrackingId": "",
      "tenantEnabled": true,
      "tenantTrackingId": "xxx"
    }
  },
  "oae-activity": {
    "activity": {
      "enabled": true
    }
  },
  "oae-mediacore": {
    "mediacore": {
      "enabled": false,
      "url": "https://ulco.mediacore.tv",
      "keyId": "5eSvCqQ0ljU",
      "secret": "xxx",
      "collectionId": "21529"
    }
  },
  "oae-content": {
    "visibility": {
      "files": "private",
      "collabdocs": "private",
      "links": "private"
    },
    "storage": {
      "backend": "local",
      "amazons3-access-key": "<access-key>",
      "amazons3-secret-key": "<secret-key>",
      "amazons3-region": "us-east-1",
      "amazons3-bucket": "oae-files"
    }
  },
  "oae-preview-processor": {
    "slideshare": {
      "apikey": "",
      "sharedsecret": ""
    },
    "flickr": {
      "apikey": "",
      "apisecret": ""
    },
    "youtube": {
      "key": ""
    }
  },
  "oae-principals": {
    "group": {
      "visibility": "private",
      "joinable": "request"
    },
    "recaptcha": {
      "enabled": true,
      "publicKey": "xxx",
      "privateKey": "xxx"
    },
    "termsAndConditions": {
      "enabled": true,
      "text": {
        "default": "## Déclaration des droits et responsabilités  \r\nAvant l'utilisation de la plateforme OAE, vous devez accepter les termes et conditions de son utilisation.\r\n\r\n###Votre Profil \r\nLes informations contenues dans votre profil nous permettent de communiquer avec vous notamment lors des mises à jour.\r\n\r\n###Partage de votre contenu et de vos informations\r\nLe contenu et les informations que vous publiez sur la plateforme OAE vous appartiennent. Vous pouvez contrôler la façon dont vous les partagez grâce aux paramètres d'accès :\r\n#####  * Lorsque vous publiez du contenu ou des informations avec le paramètre « Public », cela signifie que vous permettez à tout le monde, y compris les personnes n’utilisant pas la plateforme, d’accéder à ces informations et de les utiliser, mais aussi de les associer à vous (c’est-à-dire, votre nom et l’image de votre profil).\r\n#####  * Lors de la publication de ces contenus et informations, vous devez respecter les règles et législations applicables en France.\r\n#####  * Il est strictement interdit d'utiliser cette plateforme à des fins illégales et ou pour promouvoir des activités notamment dangereuses, illicites ou discriminatoires.\r\n\r\n###Disponibilité\r\nCette plateforme est en phase de pilote, et est gérée par une équipe Esup inter-universitaire.\r\nNous nous efforcerons d'assurer la continuité de service.\r\n\r\n###Sécurité\r\nNous faisons tout notre possible pour faire de cette plateforme un service sûr, mais ne pouvons pas garantir la sécurité absolue.\r\nTout élément lié à la sécurité sera remonté vers les correspondants de chaque établissement.\r\n\r\n###Protection des droits d’autrui\r\nNous respectons les droits d’autrui et nous vous demandons d'en faire de même.\r\n#####  * Nous nous réservons le droit de retirer tous contenus et informations que vous aurez publié sur la plateforme en cas de violation avec la présente Déclaration.\r\n#####  * En cas de violation, nous pourrons désactiver votre compte."
      }
    },
    "user": {
      "visibility": "public",
      "emailPreference": "immediate",
      "defaultLanguage": "fr_FR"
    }
  },
  "oae-tincanapi": {
    "lrs": {
      "enabled": false,
      "username": "xxx",
      "password": "xxx",
      "endpoint": "https://cloud.scorm.com/tc/3HQ4Q12B57/statements"
    }
  },
  "oae-ui": {
    "skin": {
      "variables": {
        "institutional-logo-url": "'https://portail.univ-littoral.fr/partage/sites/logobleu2.gif'",
        "branding-gradient2-color": "rgb(12, 141, 223)",
        "link-color": "rgb(8, 100, 155)",
        "link-hover-color": "rgb(0, 13, 19)"
      }
    }
  },
  "oae-uservoice": {
    "general": {
      "enabled": false,
      "baseUrl": "",
      "subdomain": "",
      "ssoKey": ""
    }
  },
  "oae-email": {
    "general": {
      "fromName": "",
      "fromAddress": ""
    }
  }
}

**Comment by sallakarppinen** [comment]
OK, that looks fine. The fact that it works for for ULCO but not for ESUP still indicates it might be config-related, or possibly a data (migration?) issue... Could you check if the locale is set correctly for a user at ESUP? Your own user for example, at /api/me?

**Comment by dooremont** [comment]
Ok for the two users : locale :"fr_FR"

**Comment by sallakarppinen** [comment]
@dooremont, it'll probably be easier to continue this discussion in Slack so I've sent you a message there.

**Comment by dooremont** [comment]
Ok but I'm in New York for the Apereo conference. Next week it's possible ...

**Comment by sallakarppinen** [comment]
Cool, get back to me when you're available.

**Comment by sallakarppinen** [comment]
@dooremont, is this problem still occurring? If it's not, can you close this issue please?

**Comment by sallakarppinen** [comment]
I'm going to close this as inactive.
