### ISSUE TITLE
Cannot create account / verify e-mail

### ISSUE THREAD

**Issue by HassHz** [oaeproject/Hilary#1302]
I just followed the installation instructions and set up a developer environment, however whenever I try to create an account on the tenant, or send a verification e-mail after signing in with twitter, i get the following error:
```
An uncaught exception was raised to the application
    TypeError: Object function juice(arg1, arg2, arg3) {
      // legacy behavior
      if (typeof arg2 === 'string') return inlineContent(arg1, arg2);
      var options = arg3 ? arg2 : {};
      var callback = arg3 ? arg3 : arg2;
      juiceFile(arg1, options, callback);
    } has no method 'juiceResources'
```
I had to downgrade the Juice module to even get OAE running because if it wasn't v 0.5.0 it was giving me an unexpected token error and wasn't even able to do anything

**Comment by sallakarppinen** [comment]
I can't reproduce this with the latest version of juice (4.0.2, released 27/11/2016). @HassHz, can you verify what version this was happening with and whether it has been fixed with a later release?

**Comment by brecke** [comment]
Inactive and unable to reproduce.
