### ISSUE TITLE
Users from a disabled tenant can be invited to a group

### ISSUE THREAD

**Issue by brecke** [oaeproject/Hilary#1304]
It has been brought to our attention that it is still possible to invite users from tenant ABC (e.g. `u:abc:...`) to a group after that tenant has been disabled. 

I'm not sure what the correct behaviour is, but it creates a somewhat incoherent state because users will still be using the system on several tenants but their own (it's been disabled).

Breaking it down into smaller tasks:

- [x] Make sure users from "rp" get disabled (migration)
- [x] Make sure users get disabled when tenancy gets disabled
- [x] ~~Disable the Activity Module when disabling a tenancy~~
- [x] Make sure deleted/disabled users can't be invited (it is possible via e-mail, I have confirmed it)
- [x] Make sure that when a user is disabled, he is obfuscated removed from all the groups he is a member of **for admins** (follow-up of #1233)

**Comment by sallakarppinen** [comment]
Note: this relates to PR #1233

**Comment by sallakarppinen** [comment]
Instead of disabling the Activity Module when a tenancy is disabled, I'll just add a check before activities are created - that way we can re-activate the tenancy with the correct setting at a later date if needed.

**Comment by brecke** [comment]
Closed by PR #1334
