### ISSUE TITLE
Running tests doesn't wait for Cassandra to drop data

### ISSUE THREAD

**Issue by brecke** [oaeproject/Hilary#1308]
Right now Cassandra is told to drop keyspace `oaeTest` but the testing code doesn't wait for it to complete and we get a lot of errors when running tests (e.g. `grunt test-module:oae-principals`).

Here's the code (from `oae-tests/runner/beforeTests.js`):

```
before(function(callback) {
    this.timeout(2000000);

    // Create the configuration for the test
    var config = TestsUtil.createInitialTestConfig();

    TestsUtil.setUpBeforeTests(config, dropKeyspaceBeforeTest, callback);
});
```

@stuartf confirmed this:

> the issue is that the `setUpTests` tells Cassandra to drop everything from the test db (which can take a little while) and then it's a race for Cassandra to do that before the tests start writing new stuff

There's a workaround though:

> I had some luck with speeding up the drop by turning off `auto_snapshot` in Cassandra's options and starting Cassandra with `JVM_OPTS="$JVM_OPTS -Dcassandra.unsafesystem=true"` both those should only be done in dev though

**Comment by sallakarppinen** [comment]
Having spent a couple of days looking at this, I haven't found an easy way to fix it... As increasing the timeout doesn't seem to help (at least for me locally) it's probably the query timing out in helenus itself. I think the next thing to try is switching out the Cassandra library we use (helenus) to a newer one (preferably the official cassandra-driver), but this is obviously a larger task. On the other hand it's one that we will have to do eventually in any case so I suggest that we start now and maybe work on it in between more pressing tasks. Thoughts?

**Comment by brecke** [comment]
It would definitely help us have a better picture of what's at stake in terms of time and effort, so I say let's give it a go and keep this thread updated with new information (e.g. subtasks, comments, etc) for future reference.

**Comment by sallakarppinen** [comment]
Cool - I have a couple of front-end tasks to look into today but will get back to this after those are done.

**Comment by brecke** [comment]
That timeout needs to be way larger in development mode. Closing.

More details in PR https://github.com/oaeproject/Hilary/pull/1421
