### ISSUE TITLE
Upgrade Node.js version to latest LTS

### ISSUE THREAD

**Issue by sallakarppinen** [oaeproject/Hilary#1336]
Take time to go over and fix use of deprecated libraries etc., update package.json, and update dependencies where we have been locked to a particular version due to node 0.10

**Comment by RobChooses** [comment]
There are a number of vulnerabilities in the npm packages as identified by nsp. Will these be updated as part of the Node update to v6, or to be done separately? Regardless of the node version, these vulnerabilities also exist in the packages locked for node 0.10.

**Comment by sallakarppinen** [comment]
That will probably need to be done separately... This task is part of a larger effort to get the project more up to date, and updating some of the dependencies is on the roadmap. We're always looking for more contributors though, so if you've identified specific packages that could be fixed feel free to make a PR! :smile:
