### ISSUE TITLE
Create method of fetching all users for a tenancy

### ISSUE THREAD

**Issue by sallakarppinen** [oaeproject/Hilary#1340]
Will probably require an extra table in Cass.

**Comment by davidoae** [comment]
Really? Duplicating data in my mind seems wrong.
Does the api not already have an endpoint for this?

Of course I'm just interfering without good knowledge.

D

**Comment by sallakarppinen** [comment]
The API does not have an endpoint for this, and there's not really any way to get the data without duplicating it considering the NoSQL nature of Cassandra... Just querying all users by `tenancyAlias` is not possible.

**Comment by brecke** [comment]
What if we make `tenantAlias` a primary key? I don't even know if that's possible, just thinking out loud.
