### ISSUE TITLE
Ability to join groups with moderation

### ISSUE THREAD

**Issue by brecke** [oaeproject/Hilary#1402]
This feature comprises two scenarios:

1. Ability to submit a join request option for visible groups

This is a request from [uservoice](https://oaeproject.uservoice.com/forums/249738-open-academic-environment/suggestions/7360843-group-join-request-option-for-visible-groups):

> Visible groups should have the option of sending a group join request to the group manager. This request should be visible in activity feed and email notifications of all managers of the group.

2. When dealing with private groups, managers are able to share a link to the group with users who then just need to click a button "join group" and that's it. This action should also have moderation.

All in all, there are several subtasks:

- [x] Join group request submission for scenario 1
- [x] Join group request submission for scenario 2
- [x] Notifications for group managers
- [x] Moderation for group managers

**Comment by ClaireLozano** [comment]
Hi, 

I've finished the developments :) 

You can find the pull requests here :
- 3akai-ux : https://github.com/oaeproject/3akai-ux/pull/4198
- Hilary : https://github.com/oaeproject/Hilary/pull/1543

Tell me if you want some screenshots of the front (to tell me if there are elements to modify).

**Comment by brecke** [comment]
> Tell me if you want some screenshots of the front (to tell me if there are elements to modify).

Yes, I do. I will test it anyway locally, but this way I'll know what to expect :)

**Comment by brecke** [comment]
All reviewed, feel free to ask me anything!
