### ISSUE TITLE
Ability to delete user (aka the right to be forgotten)

### ISSUE THREAD

**Issue by brecke** [oaeproject/Hilary#1406]
From [Open Academic Environment group](https://groups.google.com/a/apereo.org/forum/#!topic/oae/katbJUGX_Uc):

> As you probably know, the European Commission proposed a reform of the data protection regulation in the EU that we have to comply to starting May 2018.
    
> One of these rules is the "Right to be forgotten"... which is not implemented in OAE as it.
As of today, “deleting a user” means "adding a deleted flag to the entry" and that's pretty much it. The user can no longer log in but we don’t delete any of their data... Hence why we decided to modify the "delete user" function in order to make sure that all their "private" data would be actually removed.

**Comment by brecke** [comment]
Just to make sure we're in sync, I'm going to paste this from an earlier thread:

> A good way to gather all the data is just to log in and try to identify everything that may be downloaded and imported somewhere else. Let's do that:

- Personal data (picture, profile data, preferences)
- Library content (files, images, etc)
- Discussions the user has participated in
- Groups the user is part of and content within those groups
- Network: list of users following / followers

> I was thinking that perhaps we can make some of these optional? For instance, we'd open a modal box and it would present something like the image in attach. What do you think? I don't see activity events as something personal or being of any relevance in this regard.

**Comment by ClaireLozano** [comment]
Some of the data couldn't be removed (yet) : 
- Table `ActivityStreams` column `activity` : The actor of the activity is stored here, in a json object. So for now, a removed user still appears in the activity page as : 
removed user created the folders "folder" and "another folder" 
- All the tables "message box" : we only can get a message by a resourceId and not by a userId

**Comment by brecke** [comment]
Regarding the "messages" limitation, the way to do it would be to fetch all the contents a principal has access to (via `AuthzMembers` or `AuthzRoles`) and then query the messages with the `WHERE resourceId IN []` clause. Doable?

**Comment by ClaireLozano** [comment]
> Regarding the "messages" limitation, the way to do it would be to fetch all the contents a principal has access to (via AuthzMembers or AuthzRoles)

Plus all the public and 'your tenant' messages because you can leave a message on a public/tenant resource. 

There is another case : 
- the resource A is public
- the user A (who hasn't any direct role on it) let a message on resource A
- the resource A become private
- the message stay on the resource and the user A still have no right on it 

This this actual database, it's doable but with a `select * from "messageBoxTables" ;` and then select the right messages through nodejs.

But when you will have the new database, you should be able to make a query on a principalId so that will be easily doable, not like now.

**Comment by brecke** [comment]
You're right! Thanks a lot for describing the edge case. It really is too much for now, we're leaving this for now and will come back to it later. 

Going to mark this as resolved on reviewable.

**Comment by brecke** [comment]
Closing. See https://github.com/oaeproject/Hilary/pull/1779 for more info.
