### ISSUE TITLE
always 502 error page

### ISSUE THREAD

**Issue by 956237586** [oaeproject/Hilary#1419]
when i install my oae server folling the github. i always can see 500 error even i restart oae-hilary use `docker-compose restart oae-hilary`.

it seems oae-hilary can't connect to cassandra, how can i fix it ?
error log: 

oae-hilary           | [2017-07-16T12:19:36.367Z] ERROR: oae-cassandra/26 on c548108638f8: An error occurred executing a cassandra query (parameters=[])
oae-hilary           |     Error: Read Timed Out
oae-hilary           |         at Timeout._onTimeout (/usr/src/Hilary/node_modules/helenus/lib/connection.js:403:16)
oae-hilary           |         at ontimeout (timers.js:365:14)
oae-hilary           |         at tryOnTimeout (timers.js:237:5)
oae-hilary           |         at Timer.listOnTimeout (timers.js:207:5)
oae-hilary           |     --
oae-hilary           |     query: CREATE TABLE "OAuthClient" ("id" text PRIMARY KEY, "displayName" text, "secret" text, "userId" text)
oae-hilary           | [2017-07-16T12:19:36.369Z] ERROR: oae-modules/26 on c548108638f8: Error initializing module oae-authentication
oae-hilary           |     err: {
oae-hilary           |       "code": 500,
oae-hilary           |       "msg": "An error occurred executing a query"
oae-hilary           |     }
oae-hilary           | [2017-07-16T12:19:36.369Z]  INFO: oae/26 on c548108638f8: All modules are bootstrapped, initializing servers
oae-hilary           | [2017-07-16T12:19:36.370Z] ERROR: system/26 on c548108638f8: Error initializing server.
oae-hilary           |     err: {
oae-hilary           |       "code": 500,
oae-hilary           |       "msg": "An error occurred executing a query"
oae-hilary           |     }

**Comment by brecke** [comment]
Hi there @956237586 

Is the cassandra docker running properly according to logs? `docker-compose logs -f oae-cassandra`

Also, can you access it directly with `cqlsh` from you host?

**Comment by 956237586** [comment]
cqlsh command not found in my host server and oae-hilary contanier

**Comment by brecke** [comment]
Hi,

It's not installed by default in any of those, but could you try installing it with `pip` on your host to try and debug it? 

Also, is there anything in the cassandra logs that might be relevant to this issue?

**Comment by 956237586** [comment]
ping from hilary to cassandra, it ok

root@c548108638f8:/usr/src/Hilary# ping oae-cassandra
PING oae-cassandra (172.20.0.3) 56(84) bytes of data.
64 bytes from oae-cassandra.hilary_my_network (172.20.0.3): icmp_seq=1 ttl=64 time=0.805 ms
64 bytes from oae-cassandra.hilary_my_network (172.20.0.3): icmp_seq=2 ttl=64 time=0.153 ms
64 bytes from oae-cassandra.hilary_my_network (172.20.0.3): icmp_seq=3 ttl=64 time=0.222 ms
64 bytes from oae-cassandra.hilary_my_network (172.20.0.3): icmp_seq=4 ttl=64 time=0.229 ms


but when i restart hilary....



[2017-07-18T14:15:58.917Z]  INFO: oae-modules/32 on c548108638f8: Initialized module oae-tenants
[2017-07-18T14:16:09.076Z] ERROR: oae-cassandra/32 on c548108638f8: An error occurred executing a cassandra query (parameters=[])
    Error: Read Timed Out
        at Timeout._onTimeout (/usr/src/Hilary/node_modules/helenus/lib/connection.js:403:16)
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)
    --
    query: CREATE TABLE "OAuthAccessTokenByUser" ("userId" text, "clientId" text, "token" text, PRIMARY KEY ("userId", "clientId")) WITH COMPACT STORAGE
[2017-07-18T14:16:09.090Z] ERROR: oae-modules/32 on c548108638f8: Error initializing module oae-authentication
    err: {
      "code": 500,
      "msg": "An error occurred executing a query"
    }
[2017-07-18T14:16:09.092Z]  INFO: oae/32 on c548108638f8: All modules are bootstrapped, initializing servers
[2017-07-18T14:16:09.098Z] ERROR: system/32 on c548108638f8: Error initializing server.
    err: {
      "code": 500,
      "msg": "An error occurred executing a query"
    }
[2017-07-18T14:16:09.098Z]  INFO: system/32 on c548108638f8: Initialization all done ... Firing up tenants ... Enjoy!
[2017-07-18T14:16:11.336Z]  INFO: oae-server/32 on c548108638f8: Rejecting request during shutdown with 502 error (path=/api/ui/skin)
[2017-07-18T14:16:11.723Z]  INFO: oae-server/32 on c548108638f8: Rejecting request during shutdown with 502 error (path=/api/me)
[2017-07-18T14:16:12.818Z]  INFO: oae-server/32 on c548108638f8: Rejecting request during shutdown with 502 error (path=/api/me)
[2017-07-18T14:16:12.844Z]  INFO: oae-server/32 on c548108638f8: Rejecting request during shutdown with 502 error (path=/api/ui/skin)

**Comment by 956237586** [comment]
could you tell me command after run cqlsh?

**Comment by 956237586** [comment]
Successfully installed cassandra-driver-3.10 cql-1.4.0 cqlsh-5.0.4 futures-3.1.1 thrift-0.10.0
root@54fb49a5bd23:/etc# cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
root@54fb49a5bd23:/etc# cqlsh oae-cassandra
Connection error: ('Unable to connect to any servers', {'172.20.0.3': DriverException('ProtocolError returned from server while using explicitly set client protocol_version 4',)})

**Comment by brecke** [comment]
Hi there,

Have you tried this in the meantime? Things have changed a bit - new cassandra driver plus documentation improvements, etc - so I'd suggest giving it a go and see how that goes.

Thanks!

**Comment by 956237586** [comment]
Sorry! I have been gave up this project,  It took me lots of time than expected. I will try it if a have more time again.

**Comment by brecke** [comment]
Sorry to hear that. If you ever face issues again, don't hesitate and ask for help!

**Comment by 956237586** [comment]
thanks!
