### ISSUE TITLE
Add NODE_ENV

### ISSUE THREAD

**Issue by sallakarppinen** [oaeproject/Hilary#1429]
Environment variables in OAE are not being managed as well as they could be; we should separate values that change depending on environment to be fetched from NODE_ENV instead of being scattered around like they are currently.

**Comment by davidoae** [comment]
I suggest puppet add NODE_ENV to Hilary's init based on puppet's environment setting.
Are there any other locations it should be set?

**Comment by sallakarppinen** [comment]
Not that I can think of - I'm still going over the code to gather up all the random bits though.
