### ISSUE TITLE
Update etherpad to include comments

### ISSUE THREAD

**Issue by brecke** [oaeproject/Hilary#1532]
Tasks:

- [x] Update docker
- [x] Test the comments plugin
- [x] Index comments
- [x] Fork
- [x] Rename comments to annotations by changing locale on the fork
- [x] Try to work around the fact that a comment and a content edit are different events

**Comment by sallakarppinen** [comment]
Looked into comment events...By the looks of it, adding a comment created a 'malformed' message that is intercepted by `handleMessage` in ep_oae but does not contain the author data. Without this data we can't really create meaningful notifications for users as they wouldn't include who created a comment, just that a comment was created. As such I suggest we leave out comments from OAE activity feed for now.
