### ISSUE TITLE
docker-compose-up command fails because no oae-rabbitmq service is defined in docker-compose.yml

### ISSUE THREAD

**Issue by Sanil2108** [oaeproject/Hilary#2268]
**What happened:** I ran the command ` sudo docker-compose up --no-start --build oae-cassandra oae-redis oae-elasticsearch oae-hilary` as given in the README.md but it fails with the error `ERROR: No such service: oae-rabbitmq`.

There is no service by the name `oae-rabbitmq` in docker-compose.yml, hence the issue. 

**What should have happened:** The command should have ran successfully building docker containers.

**Comment by brecke** [comment]
Hi, sorry I missed this. OAE does not use rabbitmq anymore, now it's just redis. You'll find the right instructions on how to run docker containers in the README. Alternatively, you can run OAE in a single docker now: https://github.com/oaeproject/oae-demo

Hope this helps!
